// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountCard: typeof import('./src/components/AccountCard.vue')['default']
    BillingList: typeof import('./src/components/BillingList.vue')['default']
    CalculateMoney: typeof import('./src/components/CalculateMoney.vue')['default']
    CalendarChart: typeof import('./src/components/CalendarChart.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FormModal: typeof import('./src/components/FormModal.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    LoginModal: typeof import('./src/components/LoginModal.vue')['default']
    MainContent: typeof import('./src/components/MainContent.vue')['default']
    Organization: typeof import('./src/components/Organization.vue')['default']
    PieChartByCategory: typeof import('./src/components/PieChartByCategory.vue')['default']
    PieChartByTag: typeof import('./src/components/PieChartByTag.vue')['default']
    ProjectHistory: typeof import('./src/components/ProjectHistory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNav: typeof import('./src/components/TopNav.vue')['default']
  }
}
